# Generated by Django 5.0.6 on 2024-06-21 15:18

import django.db.models.deletion
import problems.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True)),
                ('time_limit', models.IntegerField(default=1)),
                ('hint', models.TextField(default='No hints in the Database')),
                ('module', models.CharField(choices=[('Loops', 'Loops'), ('Array', 'Array'), ('Recursion', 'Recursion'), ('Hashing', 'Hashing'), ('Dynamic Programming', 'Dynamic Programming'), ('Math', 'Math')], default='Array', max_length=100)),
                ('noof_solves', models.IntegerField(default=0)),
                ('noof_attempts', models.IntegerField(default=0)),
                ('problem_statement', models.TextField()),
                ('input_format', models.TextField()),
                ('output_format', models.TextField()),
                ('input_file1', models.FileField(blank=True, default=None, upload_to=problems.models.test_case_upload_path1)),
                ('output_file1', models.FileField(blank=True, upload_to=problems.models.test_case_upload_path1)),
                ('input_file2', models.FileField(blank=True, default=None, upload_to=problems.models.test_case_upload_path2)),
                ('output_file2', models.FileField(blank=True, upload_to=problems.models.test_case_upload_path2)),
                ('input_file3', models.FileField(blank=True, default=None, upload_to=problems.models.test_case_upload_path3)),
                ('output_file3', models.FileField(blank=True, upload_to=problems.models.test_case_upload_path3)),
                ('input_file4', models.FileField(blank=True, default=None, upload_to=problems.models.test_case_upload_path4)),
                ('output_file4', models.FileField(blank=True, upload_to=problems.models.test_case_upload_path4)),
                ('input_file5', models.FileField(blank=True, default=None, upload_to=problems.models.test_case_upload_path5)),
                ('output_file5', models.FileField(blank=True, upload_to=problems.models.test_case_upload_path5)),
                ('difficulty', models.CharField(choices=[('Easy', 'Easy'), ('Medium', 'Medium'), ('Hard', 'Hard')], default='Easy', max_length=20)),
                ('tags', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Accepted', 'Accepted'), ('Wrong Answer', 'Wrong Answer'), ('Time Limit Exceeded', 'Time Limit Exceeded'), ('Runtime Error', 'Runtime Error'), ('Compilation Error', 'Compilation Error')], default='Wrong Answer', max_length=100)),
                ('code', models.TextField()),
                ('failed_test_case', models.IntegerField(default=1)),
                ('time_taken', models.FloatField()),
                ('memory_taken', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='problems.problem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
